# Note make the script folder availalbe in the container
services:
  dev-con:
    container_name: arch-container
    build:
      dockerfile: ./Dockerfile
    stdin_open: true
    tty: true
    networks:
      - playground-network

networks:
  playground-network:
    name: playground-network
    driver: bridge
